### ISSUE TITLE
Issues with comments and indents

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/stylus-playground#4]
> Node: v4.2.2
> Stylus: v0.52.4

#### Write

```stylus
body
	p a
	// comment
		color red
```

#### Expect

```css
body p a {
	color: red;
}
```

#### Get

`ParseError`

***

#### Write

```stylus
body
		// comment
	p a
		color green
```

#### Expect

`ParseError`

or

```css
body p a {
	color: red;
}
```

#### Get

```css
p a {
	color: red;
}
```
