### ISSUE TITLE
Issue with children selector and optional comma

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/stylus-playground#5]
> Node: v4.2.2
> Stylus: v0.52.4

#### Write

```stylus
body
	a > b
	a > i
		color green
```

#### Expect

```css
body a > b,
body a > i {
	color: green;
}
```

#### Get

`ParseError`
